# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_loofe_wrappers", use_symbols = TRUE, package_name = "loofe")

#' @docType package
#' @usage NULL
#' @useDynLib loofe, .registration = TRUE
NULL

rust_loo_mean <- function(x) .Call(wrap__rust_loo_mean, x)

rust_loo_clustered_mean <- function(x, clust) .Call(wrap__rust_loo_clustered_mean, x, clust)


# nolint end
